config/routes.rb
Ggp2::Application.routes.draw do

  devise_for :users, controllers: {registrations: 'adapted_devise/registrations'}

  devise_scope :user do
    get 'sign_in' => 'devise/sessions#new'
    delete 'sign_out' => 'devise/sessions#destroy'
    get 'edit_account' => 'adapted_devise/registrations#edit'
  end

  resources :aggregates, except: :index
  resource  :award_ceremonies, only: :show
  resource  :badges, only: :show
  resources :champion_tips, only: [:edit, :update]
  resources :comments, only: [:new, :create, :edit, :update, :destroy]
  resource :site_notices, only: [:show]
  resources :matches, except: :index
  resources :match_results, only: [:new, :edit, :create, :update, :destroy]
  resource  :match_schedules, only: :show
  resources :match_tips, only: :show
  resource :pin_boards, only: :show
  resources :profiles, only: :show
  resource :rankings, only: :show
  resource :roots, only: :show
  resources :teams
  resources :tips, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get :edit_multiple
      post :edit_multiple
      post :update_multiple
    end
  end
  resources :users
  resources :user_tips, only: :show
  resource  :tournament_settings, only: [:edit, :update]
  resources :venues

  root :to => 'roots#show'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController

  def show
    ranking_items = RankingSets::FindCurrent.run(page: params[:page])
    @presenter = RankingPresenter.new(
        ranking_items: ranking_items,
        tournament: tournament,
        current_user_id: current_user.id)
  end
end

app/views/rankings/show.slim
- content_for(:title, t('general.ranking'))
- content_for(:subtitle, @presenter.subtitle)

#rankings.table-responsive
  ._table-full-width-xs
    table.table.table-hover
      tbody
        - for user_ranking_presenter in @presenter.user_ranking_presenters
          tr class="link-row" data-href="#{profile_path(user_ranking_presenter.user_id)}" title="#{user_ranking_presenter.full_name}"
            td._table-full-width-xs-padding-column.hidden-xs
              = "#{user_ranking_presenter.position}."
            td.hidden-xs
              ._table-value-horizontal
                = user_ranking_presenter.nickname
                - if user_ranking_presenter.titleholder?
                  '&nbsp;
                  i.fa.fa-trophy

            td._table-full-width-xs-padding-column.visible-xs
              ._table-vertical-group
                span
                  = "#{user_ranking_presenter.position}."

                span._table-nickname
                  = user_ranking_presenter.nickname
                  - if user_ranking_presenter.titleholder?
                    '&nbsp;
                    i.fa.fa-trophy
              .pull-left
                ._table-vertical-group
                  span._table-value-vertical.text-right.pull-left = user_ranking_presenter.points
                  span._table-label-vertical = t('general.point.other')
                  .clearfix
                ._table-vertical-group
                  span._table-value-vertical.text-right.pull-left = user_ranking_presenter.correct_tips_count
                  span._table-label-vertical = t('ranking.correct_tips_count')
                  .clearfix
              .pull-left
                ._table-vertical-group
                  span._table-value-vertical.text-right.pull-left = user_ranking_presenter.correct_tendency_tips_count
                  span._table-label-vertical = t('ranking.correct_tendency_tips_count')
                  .clearfix
                ._table-vertical-group
                  span._table-value-vertical.text-right.pull-left = user_ranking_presenter.badges_count
                  span._table-label-vertical = t('general.badge.other')
                  .clearfix
              .clearfix

            td.text-center.hidden-xs.hidden-sm
              ._table-value-horizontal = user_ranking_presenter.points
              ._table-label-horizontal = t('general.point.other')

            td.highest-badge.text-center.hidden-xs.hidden-sm.hidden-md style="color: #{colors[user_ranking_presenter.badge_color]}"
              = render partial: 'badges/badge_icon', locals: {icon: user_ranking_presenter.badge_icon,
                                                              title: user_ranking_presenter.badge_title}

            td.text-center.hidden-xs.hidden-sm.hidden-md
              ._table-value-horizontal = user_ranking_presenter.correct_tips_count
              ._table-label-horizontal = t('ranking.correct_tips_count')
            td.text-center.hidden-xs.hidden-sm.hidden-md
              ._table-value-horizontal = user_ranking_presenter.correct_tendency_tips_count
              ._table-label-horizontal = t('ranking.correct_tendency_tips_count')

            td.visible-md
              ._table-vertical-group
                ._table-value-vertical.text-right.pull-left = user_ranking_presenter.correct_tips_count
                ._table-label-vertical = t('ranking.correct_tips_count')
                .clearfix
              ._table-vertical-group
                ._table-value-vertical.text-right.pull-left = user_ranking_presenter.correct_tendency_tips_count
                ._table-label-vertical = t('ranking.correct_tendency_tips_count')
                .clearfix

            td.text-center.hidden-xs.hidden-sm.hidden-md
              ._table-value-horizontal = user_ranking_presenter.badges_count
              ._table-label-horizontal = t('general.badge.other')

            td.visible-sm
              ._table-vertical-group
                span._table-value-vertical.text-right.pull-left = user_ranking_presenter.points
                span._table-label-vertical = t('general.point.other')
                .clearfix
              ._table-vertical-group
                span._table-value-vertical.text-right.pull-left = user_ranking_presenter.correct_tips_count
                span._table-label-vertical = t('ranking.correct_tips_count')
                .clearfix
              ._table-vertical-group
                span._table-value-vertical.text-right.pull-left = user_ranking_presenter.correct_tendency_tips_count
                span._table-label-vertical = t('ranking.correct_tendency_tips_count')
                .clearfix

            td.visible-sm.visible-md
              ._table-vertical-group.highest-badge.text-center style="color: #{colors[user_ranking_presenter.badge_color]}"
                = render partial: 'badges/badge_icon', locals: {icon: user_ranking_presenter.badge_icon,
                                                                title: user_ranking_presenter.badge_title}
              ._table-vertical-group.text-center
                span._table-value-vertical = user_ranking_presenter.badges_count
                span._table-label-vertical = t('general.badge.other')
                .clearfix

            td.visible-xs
              ._table-vertical-group.highest-badge.text-center style="color: #{colors[user_ranking_presenter.badge_color]}"
                = render partial: 'badges/badge_icon', locals: {icon: user_ranking_presenter.badge_icon,
                                                                title: user_ranking_presenter.badge_title}

            td.text-center
              ._table-value-horizontal
              = flag_image_tag(user_ranking_presenter.champion_tip_team_abbreviation, size: 32)
              ._table-label-horizontal = user_ranking_presenter.champion_label

            td
              = link_to user_tip_path(user_ranking_presenter.user_id)
                icon.fa.fa-list title="#{t('tip.all_of', subject: user_ranking_presenter.nickname)}"


= paginate @presenter.pagination_scope

div
  small
    strong
      = "#{t('general.hint')}: "
    i.fa.fa-trophy
    '&nbsp;
    = t('help.ranking.titleholder')