config/routes.rb
Ggp2::Application.routes.draw do

  devise_for :users, controllers: {registrations: 'adapted_devise/registrations'}

  devise_scope :user do
    get 'sign_in' => 'devise/sessions#new'
    delete 'sign_out' => 'devise/sessions#destroy'
    get 'edit_account' => 'adapted_devise/registrations#edit'
  end

  resources :aggregates, except: :index
  resource  :award_ceremonies, only: :show
  resource  :badges, only: :show
  resources :champion_tips, only: [:edit, :update]
  resources :comments, only: [:new, :create, :edit, :update, :destroy]
  resource :site_notices, only: [:show]
  resources :matches, except: :index
  resources :match_results, only: [:new, :edit, :create, :update, :destroy]
  resource  :match_schedules, only: :show
  resources :match_tips, only: :show
  resource :pin_boards, only: :show
  resources :profiles, only: :show
  resource :rankings, only: :show
  resource :roots, only: :show
  resources :teams
  resources :tips, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get :edit_multiple
      post :edit_multiple
      post :update_multiple
    end
  end
  resources :users
  resources :user_tips, only: :show
  resource  :tournament_settings, only: [:edit, :update]
  resources :venues

  root :to => 'roots#show'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/views/settings/_menu.html.slim
- content_for(:title, t('general.settings'))

div.row
  div.col-xs-12
    div.hidden-xs
      ul._nav-tabbed-menu-lg.nav.nav-tabs
        = render partial: 'settings/menu_link_list', locals: {section: section}

    div.pull-left.visible-xs
      div._nav-tabbed-menu-xs.btn-group.pull-left
        button.btn.btn-primary.dropdown-toggle type="button" data-toggle="dropdown"
          = section_translation
          | &nbsp;
          span.caret
        ul.dropdown-menu role="menu"
          = render partial: 'settings/menu_link_list', locals: {section: section}

app/views/settings/_menu_link_list.html.slim
li class=('active' if section == :teams)
  = link_to Team.model_name.human_plural, teams_path
li class=('active' if section == :tournament)
  = link_to t('general.tournament'), edit_tournament_settings_path