config/routes.rb
Ggp2::Application.routes.draw do

  devise_for :users, controllers: {registrations: 'adapted_devise/registrations'}

  devise_scope :user do
    get 'sign_in' => 'devise/sessions#new'
    delete 'sign_out' => 'devise/sessions#destroy'
    get 'edit_account' => 'adapted_devise/registrations#edit'
  end

  resources :aggregates, except: :index
  resource  :award_ceremonies, only: :show
  resource  :badges, only: :show
  resources :champion_tips, only: [:edit, :update]
  resources :comments, only: [:new, :create, :edit, :update, :destroy]
  resource :site_notices, only: [:show]
  resources :matches, except: :index
  resources :match_results, only: [:new, :edit, :create, :update, :destroy]
  resource  :match_schedules, only: :show
  resources :match_tips, only: :show
  resource :pin_boards, only: :show
  resources :profiles, only: :show
  resource :rankings, only: :show
  resource :roots, only: :show
  resources :teams
  resources :tips, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get :edit_multiple
      post :edit_multiple
      post :update_multiple
    end
  end
  resources :users
  resources :user_tips, only: :show
  resource  :tournament_settings, only: [:edit, :update]
  resources :venues

  root :to => 'roots#show'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/match.rb
class Match < ActiveRecord::Base

  include ScoreValidatable

  belongs_to :aggregate
  has_many :tips, dependent: :destroy
  has_many :ranking_items, dependent: :destroy

  validates :position, presence: true, uniqueness: true, numericality: {only_integer: true, greater_than: 0, less_than_or_equal_to: 1000}
  validates :aggregate_id, presence: true
  validates :aggregate, presence: true
  validates :date, presence: true
  validate :validate_placeholder_team_1_not_eq_placeholder_team_2_besides_nil_or_blank
  validate :validate_team_1_not_equal_team_2

  [:team_1, :team_2].each do |attribute|
    belongs_to attribute, class_name: :Team

    validates attribute, presence: {if: "#{attribute}_id"}
    validates "placeholder_#{attribute}",
              presence: {if: lambda { |match| match.send(attribute).nil? }},
              length: {minimum: 3, maximum: 64}, technical_name_allowed_chars: true, allow_blank: true
  end

  def clear_result
    self.score_team_1 = nil
    self.score_team_2 = nil
  end

  def has_result?
    score_team_1.present? && score_team_2.present?
  end

  def message_name
    "#{Match.model_name.human} #{position}"
  end

  def started?
    date.past?
  end

  def tippable?
    !started?
  end

  def winner_team
    if has_result? && score_team_1 != score_team_2
      score_team_1 > score_team_2 ? team_1 : team_2
    end
  end

  #TODO test or remove
  def self.score_or_dash team_score
    team_score.nil? ? "-" : team_score
  end

  def phase
    if aggregate.parent.present?
      aggregate.parent
    else
      aggregate
    end
  end

  private

  def validate_placeholder_team_1_not_eq_placeholder_team_2_besides_nil_or_blank
    validate_to_be_eq_besides_nil_or_blank(placeholder_team_1, placeholder_team_2, :placeholder_team_2,
                                           I18n.t('errors.messages.must_not_equals_team_1_placeholder'))
  end

  def validate_team_1_not_equal_team_2
    validate_to_be_eq_besides_nil_or_blank team_1, team_2, :team_2, I18n.t('errors.messages.must_not_equals_team_1')
  end

  def validate_to_be_eq_besides_nil_or_blank value_1, value_2, key_2, error_message
    if value_1 == value_2
      errors[key_2]<< error_message unless value_1.blank?
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def new
    @match = Match.new(aggregate_id: params[:aggregate_id])
  end

  def edit
    @match = current_resource
  end

  def create
    @match = Matches::Create.run(match_attributes: params[:match])

    if @match.errors.blank?

      notice = t('model.messages.added', model: @match.message_name)

      if params[:subsequent_match]
        redirect_to new_match_path(aggregate_id: @match.aggregate_id), notice: notice
      else
        redirect_to match_schedules_path(aggregate_id: @match.aggregate_id), notice: notice
      end
    else
      render :new
    end
  end

  def update
    @match = current_resource

    if @match.update_attributes(params[:match])
      redirect_to match_schedules_path(aggregate_id: @match.aggregate_id), notice: t('model.messages.updated', model: @match.message_name)
    else
      render :edit
    end
  end

  def destroy
    @match = current_resource
    @match.destroy

    redirect_to match_schedules_path, notice: t('model.messages.destroyed', model: @match.message_name)
  end

  private

  def current_resource
    @current_resource ||= Match.find(params[:id]) if params[:id]
  end
end

app/views/matches/_form.html.slim
= simple_form_for match, html: {ole: 'form'}, defaults: {required: false} do |f|

  - aggregate = match.aggregate
  .row
    .col-xs-12.col-sm-6.col-lg-5
      = f.input :aggregate, as: :string,
                input_html: {value: aggregate.name, name: 'aggregate_name', disabled: true},
                label: aggregate.phase? ? t('general.phase.one') : t('general.group.one')
      = f.input :aggregate_id, as: :hidden

      = f.input :position, input_html: {autofocus: true}
  .row
    .col-xs-12.col-sm-6.col-lg-5
      = f.association :team_1, as: :select, collection: tournament_teams_collection_for_select
      = f.association :team_2, as: :select, collection: tournament_teams_collection_for_select
    .col-xs-12.col-sm-6.col-lg-5
      = f.input :placeholder_team_1
      = f.input :placeholder_team_2

  .form-group
    label{class="string optional control-label"} =Match.human_attribute_name(:date)
    .form-inline
      = f.input :date, label: false

  - if match.new_record?
    br
    .form-group
      .checkbox
        label
          = check_box_tag(:subsequent_match, '1', params[:subsequent_match].present?)
          = t('match.add_subsequent')

  = render partial: 'commons/form_buttons',
           locals: {form_builder: f, cancel_path: match_schedules_path(aggregate_id: match.aggregate_id)}

app/views/matches/edit.slim
- content_for(:title, t('model.messages.edit', model: "#{Match.model_name.human} #{@match.id} "))

= render partial: 'form', locals: {match: @match}

app/views/matches/index.html.erb
<%= render partial: 'commons/background_image', locals: {image_name: 'background_image_00.jpg'} %>
<% content_for(:main_title, Match.model_name.human_plural) %>

<div class="well well-sm">
  <%= link_to I18n.t('model.messages.add', model: Match.model_name.human), new_match_path, class: "btn btn-default" %>
</div>

<% if @matches.present? %>
    <div class="table-responsive">
      <table class="table table-condensed table-hover">
        <thead>
        <tr>
          <th><%= Match.human_attribute_name(:position) %></th>
          <th><%= Match.human_attribute_name(:team_1) %></th>
          <th><%= Match.human_attribute_name(:team_2) %></th>
          <th><%= I18n.t('general.match_result') %></th>
          <th><%= Match.human_attribute_name(:date) %></th>
          <th><%= Match.human_attribute_name(:aggregate) %></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @matches.each do |match| %>
            <tr class="link-row" data-href="<%= edit_match_path(match) %>">
              <td><%= match.position %> </td>
              <td>
                <% if match.team_1? %>
                    <%= image_tag("blank.gif", class: "flag flag-#{match.team_1.country.downcase}") %>
                    <span class="vertical-center"><%= match.team_1.name %></span>
                <% else %>
                    <%= match.placeholder_team_1 %>
                <% end %>
              </td>
              <td>
                <% if match.team_2? %>
                    <%= image_tag("blank.gif", class: "flag flag-#{match.team_2.country.downcase}") %>
                    <span class="vertical-center"><%= match.team_2.name %></span>
                <% else %>
                    <%= match.placeholder_team_2 %>
                <% end %>
              </td>
              <td><%= Match.score_or_dash match.score_team_1 %>:<%= Match.score_or_dash match.score_team_2 %></td>
              <td><%= I18n.l match.date, format: :short %></td>
              <td><%= match.aggregate.name unless match.aggregate.nil? %></td>
              <td>
                <%= link_to(match_path(match), method: :delete, data: {confirm: t('model.messages.destroy_really', model: ("#{Match.model_name.human} #{match.position}")), method: :delete}, title: t('model.messages.destroy', model: ("#{Match.model_name.human} #{match.position}"))) do %>
                    <i class="fa fa-trash-o"></i>
                <% end %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
<% end %>

app/views/matches/new.slim
- content_for(:title, t('model.messages.create', model: Match.model_name.human))

= render partial: 'form', locals: {match: @match}