config/routes.rb
Ggp2::Application.routes.draw do

  devise_for :users, controllers: {registrations: 'adapted_devise/registrations'}

  devise_scope :user do
    get 'sign_in' => 'devise/sessions#new'
    delete 'sign_out' => 'devise/sessions#destroy'
    get 'edit_account' => 'adapted_devise/registrations#edit'
  end

  resources :aggregates, except: :index
  resource  :award_ceremonies, only: :show
  resource  :badges, only: :show
  resources :champion_tips, only: [:edit, :update]
  resources :comments, only: [:new, :create, :edit, :update, :destroy]
  resource :site_notices, only: [:show]
  resources :matches, except: :index
  resources :match_results, only: [:new, :edit, :create, :update, :destroy]
  resource  :match_schedules, only: :show
  resources :match_tips, only: :show
  resource :pin_boards, only: :show
  resources :profiles, only: :show
  resource :rankings, only: :show
  resource :roots, only: :show
  resources :teams
  resources :tips, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get :edit_multiple
      post :edit_multiple
      post :update_multiple
    end
  end
  resources :users
  resources :user_tips, only: :show
  resource  :tournament_settings, only: [:edit, :update]
  resources :venues

  root :to => 'roots#show'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  TYPES = {
      admin: 'admin',
      player: 'player'
  }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tips, dependent: :destroy, inverse_of: :user
  has_many :ranking_items, dependent: :destroy, inverse_of: :user
  has_many :comments, dependent: :destroy
  has_many :user_badges, dependent: :destroy
  has_one :champion_tip, dependent: :destroy, inverse_of: :user

  validates :nickname, presence: true, uniqueness: true, length: {minimum: 3, maximum: 20}
  validates :first_name, presence: true, length: {maximum: 32}
  validates :last_name, presence: true, length: {maximum: 32}
  validates :admin, inclusion: {in: [true, false]}
  validates :match_sort, inclusion: {in: ['matches.position', 'matches.date']}, allow_nil: true

  scope :players, -> { where(admin: false) }
  scope :admins, -> { where(admin: true) }

  def self.find_player id
    players.where(id: id).first
  end

  def player?
    !admin?
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def message_name
    "#{User.model_name.human} \"#{first_name} #{last_name}\""
  end

  def badges_count
    user_badges.count
  end

  def most_valuable_badge
    @most_valuable_badge ||= BadgeRepository.badge_by_identifier super
  end
end

app/controllers/user_tips_controller.rb
class UserTipsController < ApplicationController

  def show

    current_aggregate = Aggregates::FindOrFindCurrentPhase.run(id: params[:aggregate_id])

    @presenter = UserTipsPresenter.new(
        user: current_resource,
        current_aggregate: current_aggregate,
        tournament: tournament,
        user_is_current_user: is_user_current_user?(current_resource)
    )

    session[Ggp2::USER_TIPS_LAST_SHOWN_AGGREGATE_ID_KEY] = params[:aggregate_id]
  end

  private

  def current_resource
    @current_resource ||= User.find_player(params[:id]) if params[:id]
  end
end

app/helpers/user_tips_helper.rb
module UserTipsHelper

  #tested by spec of _tips_table.slim
  def user_tips_table_tr_attributes(show_as_link, tip_id)
    if show_as_link
      {'class' => 'link-row', 'data-href' => "#{edit_multiple_tips_path(tip_ids: [tip_id])}"}
    else
      {}
    end
  end
end

app/views/user_tips/_champion_tip.slim
- if presenter.show?
  .well._well-full-width

    .row.hidden-xs
      .col-sm-8
        strong
          = "#{t('general.champion_tip.one', champion_title: champion_title)}"
        '&nbsp;&nbsp;
        span._emblem-with-team-name._team-name-24
          = flag_image_tag(presenter.team_abbreviation, size: 24)
          = presenter.team_name_or_missing_message
        - if presenter.tippable?
          br
          small._text-weaker
            = presenter.deadline_message
      - if presenter.tippable?
        .col-sm-4.text-right.hidden-xs
          = link_to t('model.submit.update', model: Tip.model_name.human),
              edit_champion_tip_path(presenter.id),
              class: 'btn btn-primary'

    .visible-xs
      .row
        .col-xs-8
          strong
            = "#{t('general.champion_tip.one', champion_title: champion_title)}"
          br
          span._emblem-with-team-name._team-name-24
            = flag_image_tag(presenter.team_abbreviation, size: 24)
            = presenter.team_name_or_missing_message
        .col-xs-4
          .pull-right
            - if presenter.tippable?
              = link_to t('model.submit.update', model: Tip.model_name.human),
                edit_champion_tip_path(presenter.id),
                class: 'btn btn-primary'
      - if presenter.tippable?
        small._text-weaker
          = presenter.deadline_message

app/views/user_tips/_help_modal.slim
div class="modal fade" id="help-modal" tabindex="-1" role="dialog" aria-hidden="true"
  div class="modal-dialog"
    div class="modal-content"
      div class="modal-header"
        button type="button" class="close" data-dismiss="modal" aria-hidden="true"
          '&times;
        h4 class="modal-title"
          i.fa.fa-question-circle
          = " #{t('general.help')}"
      div class="modal-body"
        p = t('help.tip.how_to_match_tip')
        p = t('help.tip.deadlines', champion_tips: t('general.champion_tip.others', champion_title: champion_title))
        p = t('help.tip.points.preface')
        ul
          li = t('help.tip.points.correct_tip',
                  points: t('general.count.point', count: Ggp2.config.correct_tip_points))
          li
             = t('help.tip.points.correct_tendency_only_tip',
                  points: t('general.count.point', count: Ggp2.config.correct_tendency_only_tip_points))
             br
             = t('help.tip.points.correct_tendency_with_score_difference',
                  points: t('general.count.point', count: Ggp2.config.correct_tendency_with_score_difference_tip_points))
             br
             = t('help.tip.points.correct_tendency_with_one_goal',
                  points: t('general.count.point', count: Ggp2.config.correct_tendency_with_one_score_tip_points))
          li = t('help.tip.points.correct_champion_tip',
                 points: t('general.count.point', count: Ggp2.config.correct_champion_tip_points),
                 champion_tip: t('general.champion_tip.one', champion_title: champion_title))

app/views/user_tips/_match_sort_form_modal.slim
div class="modal fade" id="match-sort-modal" tabindex="-1" role="dialog" aria-hidden="true"
  div class="modal-dialog"
    div class="modal-content"
      div class="modal-header"
        button type="button" class="close" data-dismiss="modal" aria-hidden="true"
          '&times;
        h4 class="modal-title"
          i.fa.fa-sort-numeric-asc
          = " #{t('model.messages.change', model: t('match.sort'))}"
      .modal-body
        = form_for current_user, html: {class: 'form-inline', role: 'form'} do |f|
          .form-group
            = f.select(:match_sort,
                       [ [Match.human_attribute_name(:position), 'matches.position'],
                         [Match.human_attribute_name(:date), 'matches.date']],
                {}, class: 'form-control')
          '&nbsp;&nbsp;
          = f.submit t('general.save'), class: 'btn btn-primary'

app/views/user_tips/_tips_table.slim
#user-tips-table
  .btn-toolbar
    - if show_as_form
      - table_id="tip-table-aggregate-#{aggregate.id}"
      - checkbox_trigger_link_id="checkbox-trigger-#{aggregate.id}"

      / Link which toggles state of all checkboxes
      /= link_to t('general.select_all'), '#', id: checkbox_trigger_link_id,  class: 'btn btn-default btn-sm', \
      /      onclick: "toggleAllCheckboxes('#{checkbox_trigger_link_id}', '#{table_id}');return false;",
      /      data: { toggle_label: t('general.select_none') }

      = link_to 'Alle tippen', '#', id: checkbox_trigger_link_id,  class: 'btn btn-default btn-sm', \
            onclick: "checkAllCheckboxesAndSubmit('#{table_id}');return false;",
            data: { toggle_label: t('general.select_none') }

      = submit_tag t('views.user_tips.show.tip_selected_matches'), class: 'btn btn-default btn-sm'
    .pull-right
      = link_to '', class: 'btn btn-default btn-sm',  data: {toggle: :modal, target: "#match-sort-modal"}
        i.fa.fa-sort-numeric-asc
        span.hidden-xs = " #{t('general.sort')}"
      = link_to '', class: 'btn btn-default btn-sm',  data: {toggle: :modal, target: "#help-modal"}
        i.fa.fa-question-circle
        span.hidden-xs = " #{t('general.help')}"

  .table-responsive
    table.table.table-hover id="#{table_id}"
      tbody
        - for tip_presenter in tip_presenters
          - match_presenter = tip_presenter.match_presenter
          - show_as_link = show_as_form && match_presenter.tippable?
          tr*user_tips_table_tr_attributes(show_as_link, tip_presenter.id)
            - if show_as_form
              td._table-full-width-xs-padding-column.text-center
                - if show_as_link
                  = check_box_tag 'tip_ids[]', tip_presenter.id
            td.hidden-xs._table-full-width-xs-padding-column
              = "#{match_presenter.position}."
            td._emblem-with-team-name._team-name-24.hidden-xs.hidden-sm
              = flag_image_tag(match_presenter.team_1_code, size: 24)
              = match_presenter.team_1_name_or_placeholder
            td._emblem-with-team-name._team-name-24.hidden-xs.hidden-sm
              = flag_image_tag(match_presenter.team_2_code, size: 24)
              = match_presenter.team_2_name_or_placeholder
            td._emblem-with-team-name._team-name-24.visible-sm
              = flag_image_tag(match_presenter.team_1_code, size: 24)
              = match_presenter.team_1_name_or_placeholder
              br
              = flag_image_tag(match_presenter.team_2_code, size: 24)
              = match_presenter.team_2_name_or_placeholder
            td.visible-xs._table-full-width-xs-padding-column
              ._text-weaker
                = "#{Match.model_name.human} #{match_presenter.position}, #{l match_presenter.date, format: :short}"
              ._emblem-with-team-name._team-16-with-emblem-24
                = flag_image_tag(match_presenter.team_1_code, size: 24)
                = match_presenter.team_1_name_or_placeholder
                br
                = flag_image_tag(match_presenter.team_2_code, size: 24)
                = match_presenter.team_2_name_or_placeholder
            td.text-center.hidden-xs
              ._table-value-horizontal = tip_presenter.result
              ._table-label-horizontal = Tip.model_name.human
            td.text-center.hidden-xs
              ._table-value-horizontal = match_presenter.result
              ._table-label-horizontal = t('general.result')
            td.text-center.hidden-xs
              ._table-value-horizontal = tip_presenter.points
              ._table-label-horizontal = t('general.point.other')
            td.visible-xs
              ._table-vertical-group
                span._table-value-vertical = tip_presenter.result
                span._table-label-vertical = Tip.model_name.human
              ._table-vertical-group
                span._table-value-vertical = match_presenter.result
                span._table-label-vertical = t('general.result')
              ._table-vertical-group
                span._table-value-vertical = tip_presenter.points
                span._table-label-vertical = t('general.point', count: tip_presenter.points)
            td.text-center._text-weaker.hidden-xs
              = l match_presenter.date, format: :only_date
              br
              = l match_presenter.date, format: :only_time
            td
              = link_to match_tip_path(match_presenter.id)
                icon.fa.fa-users title="#{t('tip.all_for', subject: "#{Match.model_name.human} #{match_presenter.position}")}"

app/views/user_tips/show.slim
- content_for(:title, @presenter.title)
- content_for(:subtitle, @presenter.subtitle)

= render partial: 'champion_tip', locals: {presenter: @presenter.champion_tip_presenter}

div.row
  div.col-xs-12
    = render partial: 'match_schedules/aggregates_menu',
             locals: {current_phase: @presenter.current_phase,
                      current_group: @presenter.current_group,
                      all_phases: @presenter.all_phases,
                      all_groups: @presenter.all_groups}

- partial_options = [\
    partial: 'tips_table',
    locals: {\
      tip_presenters: @presenter.tip_presenters,
             aggregate: @presenter.current_aggregate,
             show_as_form: @presenter.show_as_form?} \
  ]

- if @presenter.show_as_form?
  = form_tag edit_multiple_tips_path, id: 'tip-table-form'
    = render *partial_options
- else
  = render *partial_options

- unless @presenter.user_is_current_user?
  small
    strong
      = "#{t('general.hint')}: "
    = t('tip.description.for_showing_others')

= render 'match_sort_form_modal'
= render 'help_modal'